spring:
  application:
    name: spring-boot
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voca
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
hr: ${random.int}
#endpoints:
#  actuator:
#    enabled: true
#    path: /
#  autoconfig:
#    enabled: true
#autoconfig: true
management:
  security:
    enabled: false
eureka:
  client:
    eureka-server-port: 8090
    eureka-server-d-n-s-name: localhost
    eureka-server-u-r-l-context: /eureka/
    enabled: true
