spring:
  application:
    name: spring-boot
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
hr: ${random.int}
#endpoints:
#  actuator:
#    enabled: true
#    path: /
#  autoconfig:
#    enabled: true
#autoconfig: true
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true