server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://loong-mysql:3306/voca?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    eureka-server-port: 8090
    eureka-server-d-n-s-name: localhost
    eureka-server-u-r-l-context: /eureka/
    enabled: false

#  context-path: /voca
page:
  pageNum: 1
  pageSize: 20
  totalSize: ${page.pageNum} * ${page.pageSize}